---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: us-census-population
    cluster: apis.us-census-population
  name: us-census-population
  namespace: apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us-census-population
      cluster: apis.us-census-population
  template:
    metadata:
      labels:
        app: us-census-population
        cluster: apis.us-census-population
    spec:
      serviceAccountName: apis-sa
      containers:
        - name: us-census-population-proxy
          image: "docker.greymatter.io/development/gm-proxy:1.4.2"
          imagePullPolicy: IfNotPresent
          args:
            - -c
            - /etc/greymatter/config.yaml
          command:
            - /app/gm-proxy
          ports:
            - name: metrics
              containerPort: 8080
            - name: sidecar
              containerPort: 8443
          volumeMounts:
            - name: sidecar-config
              mountPath: /etc/greymatter
              readOnly: true
            - name: spire-socket
              mountPath: /run/spire/sockets
              readOnly: false
      imagePullSecrets:
        - name: docker.greymatter.io
      volumes:
        - name: spire-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
        - name: sidecar-config
          configMap:
            name: us-census-population-sidecar
