---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bls-unemployment-usa
    cluster: apis.bls-unemployment-usa
  name: bls-unemployment-usa
  namespace: apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bls-unemployment-usa
      cluster: apis.bls-unemployment-usa
  template:
    metadata:
      labels:
        app: bls-unemployment-usa
        cluster: apis.bls-unemployment-usa
    spec:
      serviceAccountName: apis-sa
      containers:
        - name: bls-unemployment-usa-proxy
          image: "docker-dev.production.deciphernow.com/deciphernow/gm-proxy:1.4.2"
          imagePullPolicy: IfNotPresent
          args:
            - -c
            - /etc/greymatter/config.yaml
          command:
            - /app/gm-proxy
          ports:
            - name: metrics
              containerPort: 8080
            - name: sidecar
              containerPort: 8443
          volumeMounts:
            - name: sidecar-config
              mountPath: /etc/greymatter
              readOnly: true
            - name: spire-socket
              mountPath: /run/spire/sockets
              readOnly: false
      imagePullSecrets:
        - name: docker-dev.production.deciphernow.com
      volumes:
        - name: spire-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
        - name: sidecar-config
          configMap:
            name: bls-unemployment-usa-sidecar
