apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: apier
    app: acaps-gov-response
    cluster: apis.acaps-gov-response
  name: acaps-gov-response
  namespace: apis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apier
      app: acaps-gov-response
      cluster: apis.acaps-gov-response
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: apier
        app: acaps-gov-response
        cluster: apis.acaps-gov-response
    spec:
      serviceAccountName: apis-sa
      containers:
      - name: apier
        env:
        - name: SHEET_NAME
          value: Database
        - name: FLASK_APP
          value: app/main.py
        - name: FLASK_DEBUG
          value: "0"
        - name: RUN
          value: flask run --host=0.0.0.0 --port=80
        - name: SOURCE_URL
          value: https://www.acaps.org/sites/acaps/files/resources/files/acaps_covid19_goverment_measures_dataset.xlsx
        image: covidapihub/apier:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - name: swagger-static
            mountPath: /app/static
            readOnly: true
      - name: sidecar
        image: "docker.greymatter.io/development/gm-proxy:1.4.2"
        imagePullPolicy: IfNotPresent
        args:
          - -c
          - /etc/greymatter/config.yaml
        command:
          - /app/gm-proxy
        ports:
          - name: metrics
            containerPort: 8080
          - name: sidecar
            containerPort: 8443
        volumeMounts:
          - name: sidecar-config
            mountPath: /etc/greymatter
            readOnly: true
          - name: spire-socket
            mountPath: /run/spire/sockets
            readOnly: false
      imagePullSecrets:
        - name: docker-dev.production.deciphernow.com
      volumes:
        - name: spire-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
        - name: sidecar-config
          configMap:
            name: acaps-gov-response-sidecar
        - name: swagger-static
          configMap:
            name: acaps-gov-response-swagger
