apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent
  namespace: spire
  labels:
    cluster: spire.agent
spec:
  selector:
    matchLabels:
      cluster: spire.agent
  template:
    metadata:
      namespace: spire
      labels:
        cluster: spire.agent
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: agent
      initContainers:
        - name: init-server
          image: gcr.io/spiffe-io/wait-for-it
          args:
            - "-t"
            - "30"
            - "server:8443"
        - name: init-registrar
          image: gcr.io/spiffe-io/wait-for-it
          args:
            - "-t"
            - "30"
            - "registrar:443"
      containers:
        - name: agent
          image: gcr.io/spiffe-io/spire-agent:0.9.2
          args:
            - "-config"
            - "/run/spire/config/agent.conf"
          volumeMounts:
            - name: agent-config
              mountPath: /run/spire/config
              readOnly: true
            - name: server-bundle
              mountPath: /run/spire/bundle
              readOnly: true
            - name: agent-socket
              mountPath: /run/spire/sockets
              readOnly: false
            - name: agent-token
              mountPath: /run/spire/tokens
              readOnly: false
          livenessProbe:
            exec:
              command:
                - /opt/spire/bin/spire-agent
                - healthcheck
                - -socketPath
                - /run/spire/sockets/agent.sock
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
      volumes:
        - name: agent-config
          configMap:
            name: agent-config
        - name: server-bundle
          configMap:
            name: server-bundle
        - name: agent-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
        - name: agent-token
          projected:
            sources:
              - serviceAccountToken:
                  path: agent
                  expirationSeconds: 7200
                  audience: server
