---
# Source: agent/templates/agent-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-dev
  namespace: spire-dev
  annotations:
    fluxcd.io/ignore: "true"
---
# Source: agent/templates/config-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config-dev
  namespace: spire-dev
  annotations:
    fluxcd.io/ignore: "true"
data:
  agent.conf: |-
    agent {
      data_dir = "/run/spire"
      log_level = "info"
      server_address = "server-dev"
      server_port = "8443"
      socket_path = "/run/spire/sockets/agent.sock"
      trust_bundle_path = "/run/spire/bundle/bundle.crt"
      trust_domain = "covidapihub.io"
      enable_sds = true
    }

    plugins {
      NodeAttestor "k8s_psat" {
        plugin_data {
          cluster = "covidapihub"
          token_path = "/run/spire/token/agent"
        }
      }

      KeyManager "memory" {
        plugin_data {
        }
      }

      WorkloadAttestor "k8s" {
        plugin_data {
          skip_kubelet_verification = true
        }
      }

      WorkloadAttestor "unix" {
          plugin_data {
          }
      }
    }
---
# Source: agent/templates/agent-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spire:agent-dev
  annotations:
    fluxcd.io/ignore: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "nodes"
      - "nodes/proxy"
    verbs:
      - "get"
---
# Source: agent/templates/agent-clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spire:agent-dev
  annotations:
    fluxcd.io/ignore: "true"
subjects:
  - kind: ServiceAccount
    name: agent-dev
    namespace: spire-dev
roleRef:
  kind: ClusterRole
  name: spire:agent-dev
  apiGroup: rbac.authorization.k8s.io
---
# Source: agent/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent-dev
  namespace: spire-dev
  labels:
    app: agent
    cluster: spire-dev.agent
  annotations:
    fluxcd.io/ignore: "true"
spec:
  selector:
    matchLabels:
      app: agent
      gmproxy: agent
      cluster: spire-dev.agent
  template:
    metadata:
      namespace: spire-dev
      labels:
        gmproxy: agent
        app: agent
        cluster: spire-dev.agent
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: agent-dev
      initContainers:
        - name: init-server
          image: gcr.io/spiffe-io/wait-for-it
          args:
            - "-t"
            - "30"
            - "server-dev:8443"
        - name: init-registrar
          image: gcr.io/spiffe-io/wait-for-it
          args:
            - "-t"
            - "30"
            - "registrar-dev:8444"
      containers:
        - name: agent
          image: gcr.io/spiffe-io/spire-agent:0.9.3
          args:
            - "-config"
            - "/run/spire/config/agent.conf"
          volumeMounts:
            - name: agent-config
              mountPath: /run/spire/config
              readOnly: true
            - name: agent-socket
              mountPath: /run/spire/sockets
              readOnly: false
            - name: server-bundle
              mountPath: /run/spire/bundle
              readOnly: true
            - name: agent-token
              mountPath: /run/spire/token
              readOnly: false
          livenessProbe:
            exec:
              command:
                - /opt/spire/bin/spire-agent
                - healthcheck
                - -socketPath
                - /run/spire/sockets/agent.sock
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
      volumes:
        - name: agent-config
          configMap:
            name: agent-config-dev
        - name: agent-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
        - name: server-bundle
          configMap:
            name: server-bundle-dev
        - name: agent-token
          projected:
            sources:
              - serviceAccountToken:
                  path: agent
                  expirationSeconds: 7200
                  audience: server-dev
