apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: spire
data:
  agent.conf: |-
    agent {
      data_dir = "/run/spire"
      log_level = "info"
      server_address = "server"
      server_port = "8443"
      socket_path = "/run/spire/sockets/agent.sock"
      trust_bundle_path = "/run/spire/bundle/bundle.crt"
      trust_domain = "covidapihub.io"
      enable_sds = true
    }

    plugins {
      NodeAttestor "k8s_sat" {
        plugin_data {
          cluster = "covidapihub"
        }
      }

      KeyManager "memory" {
        plugin_data {
        }
      }

      WorkloadAttestor "k8s" {
        plugin_data {
        }
      }

      WorkloadAttestor "unix" {
          plugin_data {
          }
      }
    }
