apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spire:agent
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "nodes"
      - "nodes/proxy"
    verbs:
      - "get"
