apiVersion: v1
kind: LimitRange
metadata:
  name: spire-lr
  namespace: spire
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 200m
    defaultRequest:
      memory: 128Mi
      cpu: 10m
    type: Container