apiVersion: v1
kind: ConfigMap
metadata:
  name: server-templates
  namespace: spire
data:
  registrar.conf.tpl: |-
    log_level = "info"
    log_path = "/dev/stdout"
    addr = "0.0.0.0:9443"
    cluster = "covidapihub"
    server_socket_path = "/run/spire/sockets/registration.sock"
    trust_domain = "covidapihub.io"
    cert_path = "/run/spire/tls/registrar.spire.svc.crt"
    key_path = "/run/spire/tls/registrar.spire.svc.key"
    cacert_path = "/run/spire/tls/ca.crt"
    insecure_skip_client_verification	= true
  server.conf.tpl: |-
    server {
      bind_address = "0.0.0.0"
      bind_port = "8443"
      registration_uds_path = "/run/spire/sockets/registration.sock"
      trust_domain = "covidapihub.io"
      data_dir = "/run/spire/data"
      log_level = "info"
      upstream_bundle = true
      svid_ttl = "1h"
      ca_subject = {
        country = ["US"],
        organization = ["Decipher Technology Studios"],
        common_name = "Covid API Hub",
      }
    }

    plugins {
      DataStore "sql" {
        plugin_data {
          database_type = "postgres"
          connection_string = "dbname={{ variable "POSTGRESQL_DATABASE" }} user={{ variable "POSTGRESQL_USERNAME" }} password={{ variable "POSTGRESQL_PASSWORD" }} host={{ variable "POSTGRESQL_HOST" }} port={{ variable "POSTGRESQL_PORT" }}"
        }
      }

      NodeAttestor "k8s_sat" {
        plugin_data {
          clusters = {
            "covidapihub" = {
              service_account_whitelist = ["spire:agent"]
              use_token_review_api_validation = true
            }
          }
        }
      }

      NodeResolver "noop" {
        plugin_data {}
      }

      KeyManager "disk" {
        plugin_data {
          keys_path = "/run/spire/data/keys.json"
        }
      }

      Notifier "k8sbundle" {
        plugin_data {
          config_map = "server-bundle"
        }
      }

      UpstreamCA "disk" {
        plugin_data {
          cert_file_path = "/run/spire/authority/intermediate.crt"
          key_file_path = "/run/spire/authority/intermediate.key"
          bundle_file_path = "/run/spire/authority/root.crt"
        }
      }
    }
