---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp:
  labels:
    io.kompose.service: apier
    app: usafacts-county-population
    cluster: apis.usafacts-county-population
  name: usafacts-county-population
  namespace: apis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apier
      app: usafacts-county-population
      cluster: apis.usafacts-county-population
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp:
      labels:
        io.kompose.service: apier
        app: usafacts-county-population
        cluster: apis.usafacts-county-population
    spec:
      serviceAccountName: apis-sa
      containers:
      - name: apier
        env:
        - name: SHEET_NAME
          value:
        - name: FLASK_APP
          value: app/main.py
        - name: FLASK_DEBUG
          value: "0"
        - name: RUN
          value: flask run --host=0.0.0.0 --port=80
        - name: SOURCE_URL
          value: https://usafactsstatic.blob.core.windows.net/public/data/covid-19/covid_county_population_usafacts.csv
        image: covidapihub/apier:sha-3be813a
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: swagger-static
          mountPath: /app/static
          readOnly: true
      - name: sidecar
        image: "docker.greymatter.io/development/gm-proxy:1.5.1"
        imagePullPolicy: IfNotPresent
        args:
        - -c
        - /etc/greymatter/config.yaml
        command:
        - /app/gm-proxy
        ports:
        - name: metrics
          containerPort: 8080
        - name: sidecar
          containerPort: 8443
        volumeMounts:
        - name: sidecar-config
          mountPath: /etc/greymatter
          readOnly: true
        - name: spire-socket
          mountPath: /run/spire/sockets
          readOnly: false
      imagePullSecrets:
      - name: docker.greymatter.io
      volumes:
      - name: spire-socket
        hostPath:
          path: /run/spire/sockets
          type: DirectoryOrCreate
      - name: sidecar-config
        configMap:
          name: usafacts-county-population-sidecar
      - name: swagger-static
        configMap:
          name: usafacts-county-population-swagger
