apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redis-data
  name: redis-data
  namespace: apis
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20G
status: {}
