apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: apier
    app: nytimes-us-counties
    cluster: apis.nytimes-us-counties
  name: nytimes-us-counties
  namespace: apis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apier
      app: nytimes-us-counties
      cluster: apis.nytimes-us-counties
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: apier
        app: nytimes-us-counties
        cluster: apis.nytimes-us-counties
    spec:
      serviceAccountName: apis-sa
      containers:
      - name: apier
        env:
        - name: SOURCE_URL
          value: https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv
        image: docker.greymatter.io/development/gm-apier:2.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        volumeMounts:
          - name: swagger-static
            mountPath: /app/static
            readOnly: true
      - name: sidecar
        image: "docker.greymatter.io/development/gm-proxy:1.5.1"
        imagePullPolicy: IfNotPresent
        args:
          - -c
          - /etc/greymatter/config.yaml
        command:
          - /app/gm-proxy
        ports:
          - name: metrics
            containerPort: 8080
          - name: sidecar
            containerPort: 8443
        volumeMounts:
          - name: sidecar-config
            mountPath: /etc/greymatter
            readOnly: true
          - name: spire-socket
            mountPath: /run/spire/sockets
            readOnly: false
      imagePullSecrets:
        - name: docker.greymatter.io
      volumes:
        - name: spire-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
        - name: sidecar-config
          configMap:
            name: nytimes-us-counties-sidecar
        - name: swagger-static
          configMap:
            name: nytimes-us-counties-swagger
