apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker.greymatter.io
  namespace: anomaly-detection
spec:
  encryptedData:
    .dockerconfigjson: AgCU2NAMaxe5suLk0OqZqhYtRPblKtIhlu9h3E5ZkY8AngEJUbGUFGnFuAXX9qPSaklb3atzJh2CB27zQSy/nzNMofnPcYZiyANQZqRub1Kivbjr18Q4wDCIiRrSUd2QBewmTYEmiblxbxHGS4xQmuyFCpTnKQ0CspyrHtWXowPe9CAbLXmGkr5IPfu+BEHRRIrtG6YvYZAcD7Ja1cid23zqvXyjplmsI6nR+l892B1McfdtRUYnol9SmAnZ1JJQIcb39f/sq/DbwuSbSJunnZD9aK3iZXPzi0AwviWuV1jSOwAaRB6y1v+1PFBaPoLbSGvqKuO7FXOViA03BkeSZ077MFevTXC2phlmDvW/feUMDb1H6mjuP5p5YX06bj+OFEeZ+bLY+E7nERVdnYJIFqbHX01kPnIXwvd0dN0gdiG04skdnufzfh77QXPUtWzSzU0VOnl/8/KL74iQM0h+cGM8C2y5Fve+MkXnU6Qz6at/2xaNupk+Ew+dUOT2QJQ9wN8PFghqqTB02TQM0HsVashc+zUjfJLpA3uuBbQy1Dzrzqc/Cn/4rFOOZyvXGwwmBdcbuq+SBwMcy46D5VjFc8961NmTZjOZDQUKYdgg1DmNsepV3SH2AGInhRaqytVGDsIVcVA7he0ocTIRNgXlP+6XLEq65gTwdRsVk2ZL/ain9iHd9PFg/E7MGm35EO0DBft1WpeX39OZZm9Cm/CBU8P7hfVZyDlL8kTUstPNhXXvuZiGnoxoZ3mIEYPKXN5vbxH89dWUUQKaeYMoD5r12MVoG+hWQnML88ym7EdQ506h5IH4behzbnn/Hjtw6XVHaKSBEOnKMZQvOmLRHPBshyNMM2OYub6aTbrwvlHMVV/tA2VCi4zlSlfsqRtVTND9GJu6jcOD1MT9y9byAWv3FfNd8OjDIbqT5eOF2rT5fgGOyEUsOdFihG6q
  template:
    metadata:
      creationTimestamp: null
      name: docker.greymatter.io
      namespace: anomaly-detection
    type: kubernetes.io/dockerconfigjson

