apiVersion: v1
kind: ConfigMap
metadata:
    name: fluent-bit-config
    namespace: anomaly-detection
    labels:
        app: fluent-bit
data:
    custom_parsers.conf: |
        [PARSER]
            Name docker_no_time
            Format json
            Time_Keep Off
            Time_Key time
            Time_Format %Y-%m-%dT%H:%M:%S.%L
    fluent-bit.conf: |
        [SERVICE]
            Flush 1
            Daemon Off
            Log_Level info
            Parsers_File parsers.conf
            Parsers_File custom_parsers.conf
            HTTP_Server On
            HTTP_Listen 0.0.0.0
            HTTP_Port 2020

        [INPUT]
            Name tail
            Path /var/log/containers/*.log
            Parser docker
            Tag kube.*
            Mem_Buf_Limit 5MB
            Skip_Long_Lines On

        [FILTER]
            Name kubernetes
            Match kube.*
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude On

        [OUTPUT]
            Name http
            Host lad.anomaly-detection.svc
            Port 8080
            URI /logs/fluent
            Format json_lines
            Match *