apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lad
  namespace: anomaly-detection
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: lad
      cluster: lad.lad
  serviceName: lad
  template:
    metadata:
      labels:
        deployment: lad
        cluster: lad.lad
    spec:
      serviceAccountName: lad
      securityContext:
        runAsUser: 1001
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: sidecar
        image: "docker.greymatter.io/development/gm-proxy:1.4.2"
        imagePullPolicy: IfNotPresent
        args:
          - -c
          - /etc/greymatter/config.yaml
        command:
          - /app/gm-proxy
        ports:
          - name: metrics
            containerPort: 8081
          - name: sidecar
            containerPort: 10808
        volumeMounts:
          - name: sidecar-config
            mountPath: /etc/greymatter
            readOnly: true
          - name: spire-socket
            mountPath: /run/spire/sockets
            readOnly: false
      - name: lad
        image: docker.greymatter.io/internal/sense-lad:latest
        imagePullPolicy: Always
        env:
          - name: LAD_INFERENCE_THREADS
            value: "3"
          - name: LAD_TRAINING_THREADS
            value: "3"
          - name: LAD_COLLECT_FOR_HOURS
            value: '72'
          - name: LAD_KUBERNETES_CLUSTER_LABEL
            value: 'cluster'
        ports:
          - containerPort: 8080
            name: lad
            protocol: TCP
        resources:
          limits:
            cpu: '4'
            memory: 5Gi
          requests:
            cpu: '2'
            memory: 2Gi
        volumeMounts:
          - name: lad-storage
            mountPath: /app/storage
      imagePullSecrets:
        - name: docker.greymatter.io
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: spire-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
        - name: sidecar-config
          configMap:
            name: lad-sidecar
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: lad-storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 25Gi
