apiVersion: v1
kind: Service
metadata:
  name: lad
  namespace: anomaly-detection
  labels:
    app: lad
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: lad
      protocol: TCP
      name: http
  selector:
    cluster: anomaly-detection-lad