---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cdc-provisional-death-counts-by-week
    cluster: apis.cdc-provisional-death-counts-by-week
  name: cdc-provisional-death-counts-by-week
  namespace: apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdc-provisional-death-counts-by-week
      cluster: apis.cdc-provisional-death-counts-by-week
  template:
    metadata:
      labels:
        app: cdc-provisional-death-counts-by-week
        cluster: apis.cdc-provisional-death-counts-by-week
    spec:
      serviceAccountName: apis-sa
      containers:
        - name: cdc-provisional-death-counts-by-week-proxy
          image: "docker.greymatter.io/development/gm-proxy:1.5.1"
          imagePullPolicy: IfNotPresent
          args:
            - -c
            - /etc/greymatter/config.yaml
          command:
            - /app/gm-proxy
          ports:
            - name: metrics
              containerPort: 8080
            - name: sidecar
              containerPort: 8443
          volumeMounts:
            - name: sidecar-config
              mountPath: /etc/greymatter
              readOnly: true
            - name: spire-socket
              mountPath: /run/spire/sockets
              readOnly: false
      imagePullSecrets:
        - name: docker.greymatter.io
      volumes:
        - name: spire-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
        - name: sidecar-config
          configMap:
            name: cdc-provisional-death-counts-by-week-sidecar
