apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: novelcovid
    cluster: apis.novelcovid
  name: novelcovid
  namespace: apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novelcovid
      cluster: apis.novelcovid
  template:
    metadata:
      labels:
        app: novelcovid
        cluster: apis.novelcovid
      creationTimestamp: null
    spec:
      containers:
      - image: docker.io/covidapihub/novelcovidapi
        imagePullPolicy: "Always"
        name: covid-api-app
        ports:
        - containerPort: 3000
        resources: {}
      - name: novelcovid-proxy
        image: "docker.production.deciphernow.com/deciphernow/gm-proxy:1.2.2"
        imagePullPolicy: IfNotPresent      
        resources: {}
        args:
          - -c
          - /etc/greymatter/config.yaml
        command:
          - /app/gm-proxy
        ports:
          - name: metrics
            containerPort: 8080
          - name: sidecar
            containerPort: 8443
        env:
          - name: ENVOY_LOG_LEVEL
            value: "debug"
        volumeMounts:
          - name: sidecar-config
            mountPath: /etc/greymatter
            readOnly: true
          - name: spire-socket
            mountPath: /run/spire/sockets
            readOnly: false
      imagePullSecrets:
        - name: docker.production.deciphernow.com
      volumes:
        - name: spire-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
        - name: sidecar-config
          configMap:
            name: novelcovid-sidecar
      restartPolicy: Always
      serviceAccountName: "apis-sa"
status: {}
