apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: apis
spec:
  encryptedData:
    password: AgCmcLV51uPSMbS1mTV87x52HBGsGa97FCaaDFsitkZ4f7OEFPu4LKmQv8ej4ps1EKVqmHAxLBpJRYTwCLz0KZFgr5eGl+iLK0R9W5oMYIDQSCaMFgxWnC9/06+5B6OsXE9DPRoHvfxN0WaTGgbhJLd9Sc/ev3aJyMNHpLU/xyy4BMY9YH8R0pAIm6c7df49W1mngDECl7m792uJdaS+VaQcitwouH/aAAw7che5T5ZCMklY+k6n5x1c7cFMDhpb/KXWC8hCTb8lyFzEtg9vuPbenrOtJCbbVMahW2ksQTvcfSUzd5GQurUpKLxut/G6sTbqVQuwwDVwzX5Ojntt03QsmyrzhVjiAMzSanPU0LZh3NdIuI9v+1RJt4HZeDobeioQ+zkUl6sBhi+pfGNtG5J1lxla4GvKZMykSR+43JGiJQu2qIPngovnVbHuBWTdm2M4MQgS+mm/7rWjeRT+y9ohjyvu2a1jMn+2c0s8KJxW//K/k3hw4Id//DR9jivb3sW6OPMduJeFrPVeGHPm58SP8a7OVEEedY7UR9oAVo1Lk2uWgqEc+6n+itBQfgY8x6BmnfqBN1/d46H/8cLBaumR5B6schgyhhHsqVXRvWlDisAWelChjtrgFd9BGn0MWwsKlqvqPtsuUD9PB9uPk53u2Lx1ebd7vAkXdWBrLuFac1bhOFHQG50/G4yMvO3yQ2Nzb2Lgc8GH7aRzNA==
  template:
    metadata:
      name: redis
      namespace: apis

