apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: redis-data
  namespace: apis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
