---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: update-checker
  namespace: apis
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.update-checker: glob:sha-*
spec:
  # Every 6 hours
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-checker
            image: novelcovid/novelcovid-api:sha-ee9c755
            command:
            - npm
            - run
            - updateCheck
            imagePullPolicy: Always
            env:
            - name: APPLE_INTERVAL
              value: "864e5"
            - name: INTERVAL
              value: "6e5"
            - name: NYT_INTERVAL
              value: "864e5"
            - name: REDIS_HOST
              value: novelcovid-redis.dvd05s.0001.use1.cache.amazonaws.com
            - name: REDIS_PORT
              value: "6379"
            - name: SERVER_PORT
              value: "3000"
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: MAILGUN_API_KEY
            - name: CAPTCHA_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: CAPTCHA_SECRET
            - name: UPDATE_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: discord-token
                  key: UPDATE_WEBHOOK
          restartPolicy: Never
          imagePullSecrets:
          - name: docker.greymatter.io
