apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
spec:
  limits:
  - default:
    max:
      cpu: 200m
      memory: 512Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: edge
  name: edge-limit-range
spec:
  limits:
  - default:
    max:
      cpu: 1
      memory: 1Gi
    type: Container
