---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cdc-cases-by-state
    cluster: apis.cdc-cases-by-state
  name: cdc-cases-by-state
  namespace: apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdc-cases-by-state
      cluster: apis.cdc-cases-by-state
  template:
    metadata:
      labels:
        app: cdc-cases-by-state
        cluster: apis.cdc-cases-by-state
    spec:
      serviceAccountName: apis-sa
      containers:
        - name: cdc-cases-by-state-proxy
          image: "docker-dev.production.deciphernow.com/deciphernow/gm-proxy:1.4.2"
          imagePullPolicy: IfNotPresent
          args:
            - -c
            - /etc/greymatter/config.yaml
          command:
            - /app/gm-proxy
          ports:
            - name: metrics
              containerPort: 8080
            - name: sidecar
              containerPort: 8443
          env:
            - name: ENVOY_LOG_LEVEL
              value: "debug"
          volumeMounts:
            - name: sidecar-config
              mountPath: /etc/greymatter
              readOnly: true
            - name: spire-socket
              mountPath: /run/spire/sockets
              readOnly: false
      imagePullSecrets:
        - name: docker-dev.production.deciphernow.com
      volumes:
        - name: spire-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
        - name: sidecar-config
          configMap:
            name: cdc-cases-by-state-sidecar
