apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::153757265334:role/eks-worker-covidapihub
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::153757265334:user/chris.smith
      username: chris.smith
      groups:
        - system:masters
    - userarn: arn:aws:iam::153757265334:user/coleman.mcfarland
      username: coleman.mcfarland
      groups:
        - system:masters
    - userarn: arn:aws:iam::153757265334:user/joshua.rutherford
      username: joshua.rutherford
      groups:
        - system:masters
    - userarn: arn:aws:iam::153757265334:user/kaitlin.moreno
      username: kaitlin.moreno
      groups:
        - system:masters
    - userarn: arn:aws:iam::153757265334:user/hiromi.suenaga
      username: hiromi.suenaga
      groups:
        - system:masters
    - userarn: arn:aws:iam::153757265334:user/zoe.mccormick
      username: zoe.mccormick
      groups:
        - system:masters
    - userarn: arn:aws:iam::153757265334:user/david.tillery
      username: david.tillery
      groups:
        - system:masters
