apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: apier
    app: tweetbinder-by-who
    cluster: apis.tweetbinder-by-who
  name: tweetbinder-by-who
  namespace: apis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apier
      app: tweetbinder-by-who
      cluster: apis.tweetbinder-by-who
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: apier
        app: tweetbinder-by-who
        cluster: apis.tweetbinder-by-who
    spec:
      serviceAccountName: apis-sa
      containers:
      - name: apier
        env:
        - name: SOURCE_FORMAT
          value: csv
        - name: SOURCE_URL
          value: https://docs.google.com/spreadsheets/d/1iP8dNUeePtLds0rhMbi1E9YaUqKIJ6F_c6zYG37yTXM/export?format=csv&gid=239842308
        - name: REDOC_URL
          value: /docs
        image: docker.greymatter.io/development/gm-apier:2.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        volumeMounts:
          - name: swagger-static
            mountPath: /app/static
            readOnly: true
      - name: sidecar
        image: "docker.greymatter.io/development/gm-proxy:1.5.1"
        imagePullPolicy: IfNotPresent
        args:
          - -c
          - /etc/greymatter/config.yaml
        command:
          - /app/gm-proxy
        ports:
          - name: metrics
            containerPort: 8080
          - name: sidecar
            containerPort: 8443
        volumeMounts:
          - name: sidecar-config
            mountPath: /etc/greymatter
            readOnly: true
          - name: spire-socket
            mountPath: /run/spire/sockets
            readOnly: false
      imagePullSecrets:
        - name: docker.greymatter.io
      volumes:
        - name: spire-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
        - name: sidecar-config
          configMap:
            name: tweetbinder-by-who-sidecar
        - name: swagger-static
          configMap:
            name: tweetbinder-by-who-swagger
