apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubeseal:controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeseal:controller
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: kubeseal
