apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: kubeseal
spec:
  ports:
    - name:
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    cluster: kubeseal.controller
  type: ClusterIP
