apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: controller
  namespace: kubeseal
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - list
