apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: kubeseal
  labels:
    cluster: kubeseal.controller
spec:
  minReadySeconds: 30
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: kubeseal.controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        cluster: kubeseal.controller
    spec:
      containers:
        - name: controller
          image: quay.io/bitnami/sealed-secrets-controller:v0.9.7
          imagePullPolicy: Always
          command:
            - controller
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
          stdin: false
          tty: false
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      securityContext:
        fsGroup: 65534
      serviceAccountName: controller
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: tmp
