apiVersion: v1
kind: LimitRange
metadata:
  name: kubeseal-lr
  namespace: kubeseal
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 200m
    defaultRequest:
      memory: 128Mi
      cpu: 100m
    type: Container