apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: proxier
  namespace: kubeseal
rules:
  - apiGroups:
      - ""
    resourceNames:
      - "http:controller:"
      - controller
    resources:
      - services/proxy
    verbs:
      - create
      - get
