apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker.production.deciphernow.com
  namespace: ingress
spec:
  encryptedData:
    .dockerconfigjson: AgA/UGtlAL/9iys9gSK4fed3EtLhwKGV5+wQHGnpqj18IocOhPqRsAY8JyHf2XFGspwGIemIFfa5vqp0/LvGmQuo3W7ZvffGI82uD/zFp1Ylw72/aSosxopMQjyMslu9TQMLEtyFUSy9n+dc7Z/y5vE2foSM5Te4H/LtRirVHpAhBstzSU7RoNZS1QmqBb3NcD6CQNlSQIemlG3iLTCBKD3rGGz/ugnB4rM428Q2/n58I+n02qg8lx/vmIXiRERMdlQaBsD1vk/O44OyZMH+VeqvUuEHmzwnCQHeZL5PsMP+XvSQKz/dmSUaQ/6cOnCbs7alUeg7NdxtJILmxGiXDefV2R/wTB4KDmJ60fhc/PdGvShS78MFBJCmtYCZCu+iLP+h7xcm8S5X6Bb2uLCeE7YdQtDQuwH0VM9c7K/2X9CUR5IqyEYVFLqPTxqq1vna11JPx68H5lezixc5nxYPZo9nc0/IvXojnh7E4UY4qX9BUqKi3GlNdVhy8nLpinJbA12RRymd5uovU59ErWk5NtSmxV99sGLuxrwiVGpJD7ZD97Aow732G4QJGMv6kir2WDGFcFxGtBJuAeplvm0ph+oqvEl+Bkq6V7+RFJADEQ+q38BLv4e7DnfLNQrPret9zHzTX2r7PdD/+S7vwj4CIGIF4S/JTIEjx688s5KE0W108EgRKe7LWI1TDK1F5DwS143S88uz6cHZT9WcUNAhwSK4oRSBELESZm66YzjT/SxEoit91Btuyegut1X4qeVXtj6xvJWvx6nyaFJy/l73LCf5uWO5/kJCZCM0YeakK8PUZbnCnhXnLOxDzWRYsAEVskHU0gaf8hszNAos670MMbtPaVjyT228SXs+x4Dzd314DWgyIGRJhPGLFIPQ9I8yLQB6IJ0JI4spJXaZGiBd//ayFcg/sbPuXZND+/X7oDf70P4uewjKukhc
  template:
    metadata:
      creationTimestamp: null
      name: docker.production.deciphernow.com
      namespace: ingress
    type: kubernetes.io/dockerconfigjson

