---
apiVersion: v1
kind: Service
metadata:
  name: edge
  namespace: ingress
  labels:
    app: edge
    cluster: ingress.edge
spec:
  ports:
    - port: 8443
      protocol: TCP
      targetPort: sidecar
  selector:
    app: edge
    cluster: ingress.edge
  type: ClusterIP
