---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: passthrough
    cluster: apis.passthrough
  name: passthrough.api
  namespace: apis
spec:
  replicas: 6
  selector:
    matchLabels:
      app: passthrough
      cluster: apis.passthrough
  strategy: {}
  template:
    metadata:
      labels:
        app: passthrough
        cluster: apis.passthrough
    spec:
      containers:
      - name: service
        env:
        - name: PORT
          value: "3000"
        - name: MESH_ID
          value: "passthrough-0"
        - name: LOG_HEADERS
          value: "true"
        image: dgoldstein1/passthrough-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 200Mi
      - name: sidecar
        image: "docker-dev.production.deciphernow.com/deciphernow/gm-proxy:1.4.3-dev"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        args:
        - -c
        - /etc/greymatter/config.yaml
        command:
        - /app/gm-proxy
        ports:
        - name: metrics
          containerPort: 8080
        - name: sidecar
          containerPort: 8443
        volumeMounts:
        - name: sidecar-config
          mountPath: /etc/greymatter
          readOnly: true
        - name: spire-socket
          mountPath: /run/spire/sockets
          readOnly: false
      imagePullSecrets:
      - name: docker-dev.production.deciphernow.com
      - name: index.docker.io
      volumes:
      - name: spire-socket
        hostPath:
          path: /run/spire/sockets
          type: DirectoryOrCreate
      - name: sidecar-config
        configMap:
          name: passthrough-sidecar
      restartPolicy: Always
      serviceAccountName: "apis-sa"
