apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker.greymatter.io
  namespace: apis
spec:
  encryptedData:
    .dockerconfigjson: AgDRvgn2nGVw53MYoClMbCWPEmmcSIaZNNV1VxkvS0c6zcOLZRpUCBnfJ+LpJAXuRKAVcP1ldv4sxC/zlxomXmIJA1tWyra0NYiQDIsz4075PrvzOJji5SOAOpmohyMjak08F0zvyg/3NhGvC5iqtNbpYqfsSF5ra9KPFsPqjrIUfdF79Tr5XT5eUGqE2gI+XtSSnn+UhZtydV8khCyoQMtM48yWipoP1UXQbHxA6xXsRGj/GKsAMacYDt7MnkX5+22YLgDp/riTDFGC+p1xxH7M6exLiLPor45QIg4Mo9BYLbKbC2ifPWcsBQPLTrw52ZQo9bRXeoes5y4B8/mhs9SAx/KzT3tnnK+FGYDtqArrJ+YOeHxW/L8nV/kpVgHIN7gsEUT3x51mw4IHWpdpdNG7ByUpV2yHvtQDp8L5s/F/WOq6rCLlSLNGWVune3IYx5g24TayRL+yteIobm+9DcBceBEYYJp0i3SXOjJ6gFq60rJoKGWWGCtyF83JQrsBorx4cLNuR/5wTvohvH4LVL305KOc56gKmHjSXfQQp46U0aBFxTGKkIKRaFprYZihBs4jeTnKsO5bYdDr78o7UDauCvWYDugn7uDt9Gmcz/UFJbKlOWGNSgrdwtHHSqqiMHAfa3oeH32xRHykrOAta/8LytKcTHDCNoJ0K1Sfy3sdiHo0MMQatXIDKfiOdD8jxrCxlpj3wiG4Rng/RHmSN7eah+5KUZUKhe7rSGLoLUqC3JEspiym/akUjTRuz9EKJ5Rosbu0OltVTDOcl8bZJISDcfgUEV6iNhDPzlQCDWCCrV2etnPVri4x4g/672YOIHzvGt3EVQwf8pycRTMoBmyfgSNrMHUDBjQ/QV4citykV5oSeKyPYo2TDwtUPmqi/toCA/aHshPagMHGZ8TqHUyaanfXRT5813j8AZmiDHMA42T5/m5+BgjHjhpDBs7W8Nx7EMiw6WiBEW5sAaTTHHd27a1d
  template:
    metadata:
      creationTimestamp: null
      name: docker.greymatter.io
      namespace: apis
    type: kubernetes.io/dockerconfigjson

