apiVersion: v1
kind: LimitRange
metadata:
  name: apis-lr
  namespace: apis
spec:
  limits:
  - default:
      cpu: 40m
      memory: 512Mi
    defaultRequest:
      cpu: 1m
      memory: 100Mi
    type: Container