apiVersion: v1
kind: LimitRange
metadata:
  name: apis-lr
  namespace: apis
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 200m
    defaultRequest:
      memory: 128Mi
      cpu: 100m
    type: Container