---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cms-hospitals-with-medicare
    cluster: apis.cms-hospitals-with-medicare
  name: cms-hospitals-with-medicare
  namespace: apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms-hospitals-with-medicare
      cluster: apis.cms-hospitals-with-medicare
  template:
    metadata:
      labels:
        app: cms-hospitals-with-medicare
        cluster: apis.cms-hospitals-with-medicare
    spec:
      serviceAccountName: apis-sa
      containers:
        - name: cms-hospitals-with-medicare-proxy
          image: "docker.greymatter.io/development/gm-proxy:1.4.2"
          imagePullPolicy: IfNotPresent
          args:
            - -c
            - /etc/greymatter/config.yaml
          command:
            - /app/gm-proxy
          ports:
            - name: metrics
              containerPort: 8080
            - name: sidecar
              containerPort: 8443
          volumeMounts:
            - name: sidecar-config
              mountPath: /etc/greymatter
              readOnly: true
            - name: spire-socket
              mountPath: /run/spire/sockets
              readOnly: false
      imagePullSecrets:
        - name: docker-dev.production.deciphernow.com
      volumes:
        - name: spire-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
        - name: sidecar-config
          configMap:
            name: cms-hospitals-with-medicare-sidecar
