---
apiVersion: v1
kind: Service
metadata:
  name: api-caw-sh-svc
  namespace: apis
  labels:
    app: novelcovid
    cluster: apis.novelcovid
spec:
  ports:
    - name: http
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: novelcovid
    cluster: apis.novelcovid
  type: ClusterIP
