---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: edge
  namespace: edge
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
    - hosts:
        - covidapihub-io.greymatter.services
        - www-covidapihub-io.greymatter.services
      secretName: covidapihub.io
  rules:
    - host: covidapihub-io.greymatter.services
      http:
        paths:
          - path: /login
            backend:
              serviceName: edge
              servicePort: 9443
          - path: /login/(.*)
            backend:
              serviceName: edge
              servicePort: 9443
          - path: /(.*)
            backend:
              serviceName: edge
              servicePort: 8443
    - host: www-covidapihub-io.greymatter.services
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: edge
              servicePort: 8443
