---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: disease.sh.ingress
  namespace: edge
  annotations:
    kubernetes.io/ingress.class: nginx-disease
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_cache api;
      proxy_cache_valid any 10m;
      proxy_cache_lock on;
      proxy_cache_use_stale error timeout updating http_404 http_500 http_502 http_503 http_504;
      proxy_ignore_headers Cache-Control;
      proxy_hide_header Cache-Control;
      add_header Cache-Control "public, max-age=14400";
      add_header NG-Cache-Status $upstream_cache_status;
      add_header NG-Key $scheme$request_method$host$request_uri;
spec:
  tls:
    - hosts: 
      - disease-sh-one-three.greymatter.services
      - www-disease-sh-one-three.greymatter.services
      - 9kzzzfwgnwgef8dc-disease-sh-one-three.greymatter.services
      - ev3klr6bchdcdowp-disease-sh-one-three.greymatter.services
      - tvf5ksnujo01bafz-disease-sh-one-three.greymatter.services
      secretName: disease.sh
  rules:
    - host: disease-sh-one-three.greymatter.services
      http:
        paths:
          - path: /
            backend:
              serviceName: disease
              servicePort: 8443
    - host: www-disease-sh-one-three.greymatter.services
      http:
        paths:
          - path: /
            backend:
              serviceName: disease
              servicePort: 8443
    - host: 9kzzzfwgnwgef8dc-disease-sh-one-three.greymatter.services
      http:
        paths:
          - path: /
            backend:
              serviceName: disease
              servicePort: 8443
    - host: ev3klr6bchdcdowp-disease-sh-one-three.greymatter.services
      http:
        paths:
          - path: /
            backend:
              serviceName: disease
              servicePort: 8443
    - host: tvf5ksnujo01bafz-disease-sh-one-three.greymatter.services
      http:
        paths:
          - path: /
            backend:
              serviceName: disease
              servicePort: 8443

