---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: disease.ingress
  namespace: edge
  labels:
    app.kubernetes.io/name: disease.ingress
    app.kubernetes.io/part-of: disease.ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: disease.ingress
subjects:
  - kind: ServiceAccount
    name: disease.ingress
    namespace: edge
