---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: edge
  labels:
    app.kubernetes.io/name: disease.ingress
    app.kubernetes.io/part-of: disease.ingress
data:
  use-proxy-protocol: "true"
