---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: disease.sh.ingress
  namespace: edge
  annotations:
    kubernetes.io/ingress.class: nginx-disease
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_cache api;
      proxy_cache_valid any 10m;
      proxy_cache_lock on;
      proxy_cache_use_stale error timeout updating http_404 http_500 http_502 http_503 http_504;
      proxy_ignore_headers Cache-Control;
      proxy_hide_header Cache-Control;
      add_header Cache-Control "public, max-age=14400";
      add_header NG-Cache-Status $upstream_cache_status;
      add_header NG-Key $scheme$request_method$host$request_uri;

spec:
  tls:
    - hosts: 
      - disease.sh
      secretName: disease.sh
  rules:
    - host: disease.sh
      http:
        paths:
          - path: /
            backend:
              serviceName: disease
              servicePort: 8443
