---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: disease-ingress
  namespace: edge
spec:
  replicas: 12
  selector:
    matchLabels:
      app.kubernetes.io/name: disease-ingress
      app.kubernetes.io/part-of: disease-ingress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: disease-ingress
        app.kubernetes.io/part-of: disease-ingress
      annotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
    spec:
      terminationGracePeriodSeconds: 300
      serviceAccountName: disease-ingress
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: disease-ingress
          image: nginx/nginx-ingress:1.7.1
          args:
            - /nginx-ingress-controller
            - --configmap=$(POD_NAMESPACE)/disease.nginx
            - --tcp-services-configmap=$(POD_NAMESPACE)/disease.tcp
            - --udp-services-configmap=$(POD_NAMESPACE)/disease.udp
            - --publish-service=$(POD_NAMESPACE)/disease-ingress
            - --annotations-prefix=nginx.ingress.kubernetes.io
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
            runAsUser: 101
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: stats
              containerPort: 8080
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          lifecycle:
            preStop:
              exec:
                command:
                  - /wait-shutdown
