---
apiVersion: v1
kind: ConfigMap
metadata:
  name: disease.nginx
  namespace: edge
  labels:
    app.kubernetes.io/name: disease-ingress
    app.kubernetes.io/part-of: disease-ingress
data:
  use-proxy-protocol: "true"
  http-snippet: |
    proxy_cache_path /etc/nginx/cache levels=1:2 keys_zone=api:20m max_size=10g inactive=1m use_temp_path=off;
    proxy_cache_key $scheme$proxy_host$request_uri;
    proxy_cache_lock on;
    proxy_cache_use_stale updating;