---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: disease
    cluster: disease
  name: disease
  namespace: edge
spec:
  replicas: 5
  selector:
    matchLabels:
      app: disease
      cluster: disease
  template:
    metadata:
      labels:
        app: disease
        cluster: disease
    spec:
      serviceAccountName: edge
      containers:
        - name: disease
          image: "docker-dev.production.deciphernow.com/deciphernow/gm-proxy:1.4.2"
          imagePullPolicy: IfNotPresent
          args:
            - -c
            - /etc/greymatter/config.yaml
          command:
            - /app/gm-proxy
          ports:
            - name: metrics
              containerPort: 8080
            - name: sidecar
              containerPort: 8443
          resources:
            limits:
              cpu: 500m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 100Mi
          volumeMounts:
            - name: sidecar-config
              mountPath: /etc/greymatter
              readOnly: true
            - name: sidecar-tls
              mountPath: /etc/tls
              readOnly: true
            - name: spire-socket
              mountPath: /run/spire/sockets
              readOnly: false
          env:
          - name: METRICS_KEY_FUNCTION
            value: depth
      imagePullSecrets:
        - name: docker-dev.production.deciphernow.com
      volumes:
        - name: sidecar-config
          configMap:
            name: disease
        - name: sidecar-tls
          secret:
            secretName: edge.svc

        - name: spire-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
