apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker.greymatter.io
  namespace: edge
spec:
  encryptedData:
    .dockerconfigjson: AgDIHw2wCXyAae0e4Mq+655gwA+bwnNMzVoQ586UXGXmGP+gHdn1iZ0Kbu9M6+r85HJNSvHR1/WIVC8KNj/kfuuszHnIjiF9IHWBpLsVLE5DYSF2kF+IpEATwKIZiLsPqIoMYgF+nJtFZp7kCQ7Tec/hgGMIxZaMvOJsdlp53j5S5Pd/KYa14GXIH+R0DFqfQkQBHVxMrf0QVDZ3nOWWIdM1TiWYaZtUgTAguN+qiV/L3JITTp11gYejKzBWYmRMXqVxgiiNefiDTE2QFbJDauf/xBWgeXw4pm7Fu8ruq+9sAcJ22gZP+AlqgQzNbtqkQYMZZ52Vlap4+OdwRI3aQrzvV5HGIIIoyeWhmIB/l7nN5VzoQC9ObgQG9Td6GgGyky0h4J258XnscnbwFfOK7AWCdsPwm5cFOI/8/5DS3TU/35nfnwTXVLr2HfatUgkufOXKD82jg6C3FBgp7OOPLY9Ni3rVP81jRMra79YILS01Swjhg5tRuuwC/ST//QPY9EJCsxSwdOgdb3TYcPISqwGIB9YVYgOiT/kKYk/KtVdK8IG1BxCECHa3QM/hBw9bAJeMR/g2lP0EZc+JmWfSs6j20lJYlMYsH+GHhka0ndPaBcqvndrtQAU2P4rxwXgdDB7cYQlcpnBwvQa8iAI5JVzkUhYbGlD3x3zJWserlW4c8JfD3/OGf74TTc8XaCV7Qc1lZVEUzKN2LAJ3esOqDri/wreOanrFSHn7j1Y4oWGbcyvhEXcADcftlRuhcZMZkEQAIBTCqyLEHqxiQT+TQ3hplGrigTOCoTIP9hP5NzAlYJ+Oxlvlfdr+PMcSFqL/a09Iekk7s24KjzV0FVdeD55pbEtWS3nL88Z9A4yi/l5mo0dq6IBTJU4tfMCBoyxkscw4WaEOZ9OJnXO6DYyQYgLi/Ksn8IBEjL8MvwibciaJw9g22Gfv9YnQ59s5voM/tkUWQBm7jnxGvojmS5cLtAYq3Vmy
  template:
    metadata:
      creationTimestamp: null
      name: docker.greymatter.io
      namespace: edge
    type: kubernetes.io/dockerconfigjson

