apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker.greymatter.io
  namespace: edge
spec:
  encryptedData:
    .dockerconfigjson: AgBNxKM3IKBW/sgN8Pj7vh4gFPGY7dAtLIRx/RLkpt0OatqOYgDsxtJWp+CybqV8bkFTiJ58hWtN824W6/1/QYC4pRZ/H7XH/hElBQ6QxR0dZV//d1RIdhpVM2n4hGycw/q0RZRV8rEv+ieEIK9CKYekXOwNQSfILE6Viw7ZT2WtnOrI/QjyRocGG82XZpcOpw9c3dO0xV6WV51dGX35IKNpnA9D3QeblOF23xRWe/9kVtSrTY/LsU1cuW15iaQF6B55Tb5UD7Tz9w9wbR076cjeEvWM2bnVISYcBE2HF9HMaWTtss9t8QACWjgZuvOXqSWJ6mnviJtXV/3K5QNQxNwXK4hir5d/7kGIUwC+PgA3M9IPBWRGF8lWdlNa3JdXK8yx9nPl4nfm7AC4uakqUa5PjtULwmZWa5Y6yJRA/v0NVTM6xRnatgbiiccD7ilxRjrRd1j4Boxr2oAtvB6Ickq2KHN+c3OUEjXOwcaDv6LgBTDg+GeVAttrXzriGp9H+2SwQG5911NIkSSqO7M0ysAFk8OnX/7AIbNpub8LLIvYC67t9UDKc3YdJBMyTzeQrtt3m+jruCZRryTFaPIUSb2ODNBKxesvJks1ML+pCtmWSORkT7ruxfx3LTipKe7eBVnoj7PsdOvpkS8R4TMpVzRsLBz/GhO8eU+2QT++4/300wXunBxW0jNlRt1pV03O6kWfZaWD3YwsP7kjfS9E0MmxXfQMm+DFeQVtU+U0Xniz3HmF4m5qfqGLdhw7lvkG8d3wdIUio7Chw1dbb0BoD7SqJ6SumBqNQRhjZYzB1m60JT9EBoCsfWXBdZxoG0xS1uGZpQ13RG/Wy5Nxv8iQivjPWnFlXEZTtF8apIjwnviCdQdvnu1nXkA9WQAeufFXYKcTT8faZCHuCfrsKTkvdx0aAxlms/6lfuKzf7rLUeHWfXH0xxZ2wI9Az2vs3/0NQs0HGstdYzuIbfgMIkalINksNT7X
  template:
    metadata:
      creationTimestamp: null
      name: docker.greymatter.io
      namespace: edge
    type: kubernetes.io/dockerconfigjson

