---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: edge
    cluster: edge.edge
  name: edge
  namespace: edge
spec:
  replicas: 6
  selector:
    matchLabels:
      app: edge
      cluster: edge.edge
  template:
    metadata:
      labels:
        app: edge
        cluster: edge.edge
    spec:
      serviceAccountName: edge
      containers:
        - name: edge
          image: "docker-dev.production.deciphernow.com/deciphernow/gm-proxy:1.4.2"
          imagePullPolicy: IfNotPresent
          args:
            - -c
            - /etc/greymatter/config.yaml
          command:
            - /app/gm-proxy
          ports:
            - name: metrics
              containerPort: 8080
            - name: sidecar
              containerPort: 8443
            - name: login
              containerPort: 9443
            - name: novelcovid
              containerPort: 7443
          volumeMounts:
            - name: sidecar-config
              mountPath: /etc/greymatter
              readOnly: true
            - name: sidecar-tls
              mountPath: /etc/tls
              readOnly: true
            - name: spire-socket
              mountPath: /run/spire/sockets
              readOnly: false
          env:
          - name: METRICS_KEY_FUNCTION
            value: depth
      imagePullSecrets:
        - name: docker-dev.production.deciphernow.com
      volumes:
        - name: sidecar-config
          configMap:
            name: edge-sidecar
        - name: sidecar-tls
          secret:
            secretName: edge.svc

        - name: spire-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
