---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: edge
  labels:
    app.kubernetes.io/name: ingress
    app.kubernetes.io/part-of: ingress
data:
  proxy-body-size: "0"
  proxy-buffering: "off"
  use-proxy-protocol: "true"
  http-snippet: |
    proxy_cache_path /etc/nginx/cache levels=1:2 keys_zone=api:20m max_size=10g use_temp_path=off;
    proxy_cache_key $scheme$request_method$host$request_uri;