---
apiVersion: v1
kind: LimitRange
metadata:
  name: ingress
  namespace: edge
  labels:
    app.kubernetes.io/name: ingress
    app.kubernetes.io/part-of: ingress
spec:
  limits:
    - default:
     
        memory: 90Mi
        cpu: 100m
      type: Container
