apiVersion: v1
kind: LimitRange
metadata:
  name: edge-lr
  namespace: edge
spec:
  limits:
  - default:
      memory: 1Gi
      cpu: 200m
    defaultRequest:
      memory: 128Mi
      cpu: 30m
    type: Container