---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit
  namespace: edge
data:
  config.yaml: |-
    ---
    domain: edge
    descriptors:
      - key: covidapihub.io
        value: "/"
        rate_limit:
          unit: second
          requests_per_unit: 1000
      - key: disease.sh
        value: "/"
        rate_limit:
          unit: second
          requests_per_unit: 10000
      - key: api.caw.sh
        value: "/"
        rate_limit:
          unit: second
          requests_per_unit: 1000
