---
kind: Service
apiVersion: v1
metadata:
  name: ratelimit
  namespace: edge
spec:
  ports:
    - name: server
      port: 8081
      protocol: TCP
      targetPort: 8001
  selector:
    cluster: edge.ratelimit
  sessionAffinity: None
  type: ClusterIP