---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ratelimit
    cluster: edge.ratelimit
  name: ratelimit
  namespace: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratelimit
      cluster: edge.ratelimit
  template:
    metadata:
      labels:
        app: ratelimit
        cluster: edge.ratelimit
    spec:
      serviceAccountName: edge
      containers:
        - name: ratelimit
          image: "envoyproxy/ratelimit:v1.4.0"
          imagePullPolicy: IfNotPresent
          env:
          - name: USE_STATSD
            value: "false"
          - name: LOG_LEVEL
            value: "debug"
          - name: REDIS_SOCKET_TYPE
            value: "tcp"
          - name: REDIS_URL
            value: "redis.edge.svc:6379"
          - name: REDIS_AUTH
            valueFrom:
              secretKeyRef:
                name: redis
                key: password

          - name: RUNTIME_ROOT
            value: "/"
          - name: RUNTIME_SUBDIRECTORY
            value: "ratelimit"
          command: ["/bin/sh","-c"]
          args: ["mkdir -p /ratelimit/config && cp /data/ratelimit/config/config.yaml /ratelimit/config/config.yaml && cat /ratelimit/config/config.yaml &&  /bin/ratelimit"]
          ports:
            - name: server
              containerPort: 8081
            - name: debug
              containerPort: 6070
          volumeMounts:
            - name: ratelimit-config
              mountPath: /data/ratelimit/config
              readOnly: true
      volumes:
        - name: ratelimit-config
          configMap:
            name: ratelimit
