---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit
  namespace: edge
data:
  config.yaml: |-
    ---
    domain: edge
    descriptors:
      - key: path
        value: "/"
        rate_limit:
          unit: second
          requests_per_unit: 100
