---
kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: edge
spec:
  ports:
    - name: server
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    cluster: edge.redis
  sessionAffinity: None
  type: ClusterIP