apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: edge
spec:
  encryptedData:
    password: AgBvILqsIvy/1XPH7WyffYFEr1JtFmndfPl1z9X+WIzM0/dat3OXa0FQpi4Xssur/E7WmEOF/92gfQAd7ALmnC0mZwhTZhASQrexADlM0Meud8yzoukodMmlMhWDhTD4qwJIwmB6X+PEamPJaWDXZado38frA5ftHcp6cAU/wU2swCOkhaRhlc3G+HpAPuntZO/vLgLPEz2Yi5JjU26D/b2n0Gqhj5nakowv/JxwgOzPEf5P2NyR6gLlRn3/XcA612lLLOKjZpMw1HiyKzvryGDEbmK45XePd+lkG0BgjcE9ahmpdXqIAShR7FkAR2blI0tGWbrWcfIR2S22q/KNe5UppFT+5+eNYFSevJ32T1xetbKqd7kzLAgmepJ0pdlL3PJ6S997QXWF9uhg8PLNY6KiUjl6pirTchmBaNNEUZ98RvtG/TpjKxYZMOLkJdhX90Esqf7R4NW032OZrfer0ADszC9tcq8p5tCWL3mRr+Fgzf1K18ahIKa4VPDYjaiFw+RuXOM4lRk8iGpOfh400YgeetHJcqcBE31vSGRclOhrn45ZyeTtzEwTE2EcnKca4LguEiZyOJ6xSAOfYIJeVezqkrun9hSYmOiPrvX762IYv83TVBUrnJmwyBi780e3uSvwI/z0NVlrdg1oGP5OsqRusD2umpbgacWfml+2MaxUiRoYmHlZEqsEqckKgWNmVn1vg5cMaGQIMfPLYdmb38S65mNkmzzcc/zxP3E2w+6FKQZeOaU=
  template:
    metadata:
      creationTimestamp: null
      name: redis
      namespace: edge

