apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
  labels:
    cluster: flux.flux
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster: flux.flux
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/port: "3031"
      labels:
        cluster: flux.flux
    spec:
      serviceAccountName: flux
      containers:
        - name: flux
          image: docker.io/fluxcd/flux:1.17.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          ports:
            - name: http
              containerPort: 3030
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 3030
              path: /api/flux/v6/identity.pub
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: 3030
              path: /api/flux/v6/identity.pub
            initialDelaySeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: git-key
              mountPath: /etc/fluxd/ssh
              readOnly: true
            - name: git-keygen
              mountPath: /var/fluxd/keygen
          args:
            - --memcached-service=
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-url=git@github.com:greymatter-io/flux-covidapihub
            - --git-branch=master
            - --git-label=flux
            - --git-user=joshua-rutherford
            - --git-email=joshua-rutherford@users.noreply.github.com
            - --git-readonly
            - --k8s-secret-name=flux
            - --listen-metrics=:3031
            - --sync-garbage-collection
      volumes:
        - name: git-key
          secret:
            secretName: flux
            defaultMode: 0400
        - name: git-keygen
          emptyDir:
            medium: Memory
