apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: flux:flux
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: flux
roleRef:
  kind: ClusterRole
  name: flux:flux
  apiGroup: rbac.authorization.k8s.io
