apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: flux
spec:
  ports:
    - name: memcached
      port: 11211
      protocol: TCP
      targetPort: 11211
  selector:
    cluster: flux.memcached
