apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: flux
  labels:
    cluster: flux.memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster: flux.memcached
  template:
    metadata:
      labels:
        cluster: flux.memcached
    spec:
      containers:
        - name: memcached
          image: memcached:1.5.20
          imagePullPolicy: IfNotPresent
          args:
            - -m 512
            - -I 5m
            - -p 11211
          ports:
            - name: clients
              containerPort: 11211
              protocol: TCP
          securityContext:
            runAsUser: 11211
            runAsGroup: 11211
            allowPrivilegeEscalation: false
