apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker.greymatter.io
  namespace: website
spec:
  encryptedData:
    .dockerconfigjson: AgAyTmfukHW8yRJTDFS5iQN9R9VUdogAn4rAjnxBm+sCLLoMroYtKbulkIc3O5zlIyWorXYbEq8AQ81OVeoEXKXNX/IJIHfiE70h2CB4xDCOgeiTF4gcXUPsmrTsA9t0Mt15R6W/R4pGcpQPjziqM4NGatRDtreVv6jyFkFQRH8kFWNAClmcoNBwqK7EoHLSl17k835ampFoTyIOwko+A0anmR8jmip6Vz1vDn9w91CvmtVFm3rK3ybNNqo3b/MToENS8YuAnXuUBcddF2qmundjTBnIwZ/ZhAO2/4f2g/zvObc2kQ4p8E8Q4uyeM3IpMJeLNBIqz52jLtK/dpKJ/EVIongD8N4a4E1zJB667nOxEI5SbGk7ltKTp6oz+TiPAFWgy36ACDOQDYyJO5wI2DBINFwjNGIwJ+9ULJJ8W2i6+gxWWDljBbgXtME3RSGEmIqdMe4uDV9C1TuVokNs1A8v1yq4Wdf7Dqfk+Ya8P826Dsi7tf2wfcDyLC/pmc0VrjgJ8yxqDm9P2K46USLJqQnRUglGu9DXkoT/+MmJTySm/SPOf94U1Sz96Ft8e8tfS7PSkCixG4va21QJVAiWYt3m7rkDpIVwjk+cptiiLh3ZQLxZ/6rlbLojmavEtrtDAeOa91deAZGvAR0mscaQ/5RAYnh0jN28oYuZOX+TBvI8LRPY1KIgn9/id8n7iGiGsv54gsaqViAU0nhw3UiZi6ntI7v2l4ulkE2AzRX1RWHx1NFE5fiO0DmHI6zwPNqHVXL8Q9ey56309lD7irsSh2JL+8qvZ1p4LanegnzkSrSMD0OoOwDpiGtxTR3hpblZU/HEgck1Vi8+jSd6fseWLusXUH0tdp3vuXOzPzsvBJ9GyVbh4qSRPmBqen41a4pHmydPA8kBlkqpiyfc6GHIGKTnuTUDMLWq5GyuPKZb77Nu4NKqC57Ji2r0st0p+gwR296OM0P3RnPnu2CgGoX7VCgX2xL5
  template:
    metadata:
      creationTimestamp: null
      name: docker.greymatter.io
      namespace: website
    type: kubernetes.io/dockerconfigjson

