apiVersion: v1
kind: LimitRange
metadata:
  name: website-lr
  namespace: website
spec:
  limits:
  - default:
      cpu: 40m
      memory: 512Mi
    defaultRequest:
      cpu: 20m
      memory: 100Mi
    type: Container