apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: apier
    app: inform-mid2020
    cluster: apis.inform-mid2020
  name: inform-mid2020
  namespace: apis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apier
      app: inform-mid2020
      cluster: apis.inform-mid2020
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: apier
        app: inform-mid2020
        cluster: apis.inform-mid2020
    spec:
      serviceAccountName: apis-sa
      containers:
      - name: apier
        env:
        - name: SHEET_NAME
          value: INFORM Risk Mid2020 (a-z)
        - name: FLASK_APP
          value: app/main.py
        - name: SHEET_SKIP_ROWS
          value: 0,2,194,195,196,197
        - name: SOURCE_FORMAT
          value: XLSX
        - name: FLASK_DEBUG
          value: "0"
        - name: RUN
          value: flask run --host=0.0.0.0 --port=80
        - name: SOURCE_URL
          value: https://drmkc.jrc.ec.europa.eu/inform-index/Portals/0/InfoRM/2020/INFORM_Risk_Mid2020_v041.xlsx?ver=2020-04-03-170624-200
        image: covidapihub/apier:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - name: swagger-static
            mountPath: /app/static
            readOnly: true
      - name: sidecar
        image: "docker.greymatter.io/development/gm-proxy:1.4.2"
        imagePullPolicy: IfNotPresent
        args:
          - -c
          - /etc/greymatter/config.yaml
        command:
          - /app/gm-proxy
        ports:
          - name: metrics
            containerPort: 8080
          - name: sidecar
            containerPort: 8443
        volumeMounts:
          - name: sidecar-config
            mountPath: /etc/greymatter
            readOnly: true
          - name: spire-socket
            mountPath: /run/spire/sockets
            readOnly: false
      imagePullSecrets:
        - name: docker-dev.production.deciphernow.com
      volumes:
        - name: spire-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
        - name: sidecar-config
          configMap:
            name: inform-mid2020-sidecar
        - name: swagger-static
          configMap:
            name: inform-mid2020-swagger
