---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: observables
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/nginx/access.log
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

    processors:
      - add_cloud_metadata:
      - add_host_metadata:

      output.logstash:
        # The Logstash hosts
        hosts: ["logstash:5044"]