apiVersion: v1
kind: ConfigMap
metadata:
    name: fluent-bit
    namespace: observables
    labels:
        app: fluent-bit
data:
    custom_parsers.conf: |
        [PARSER]
            Name docker_no_time
            Format json
            Time_Keep Off
            Time_Key time
            Time_Format %Y-%m-%dT%H:%M:%S.%L
    fluent-bit.conf: |
        [SERVICE]
            Flush 1
            Daemon Off
            Log_Level info
            Parsers_File parsers.conf
            Parsers_File custom_parsers.conf
            HTTP_Server On
            HTTP_Listen 0.0.0.0
            HTTP_Port 2020

        [INPUT]
            Name tail
            Path /var/log/containers/*.log
            Parser docker
            Tag kube.*
            Mem_Buf_Limit 5MB
            Skip_Long_Lines On
            Ignore_Older 10m

        [FILTER]
            Name kubernetes
            Match kube.*
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude On

        [FILTER]
            Name grep
            Match *
            Regex eventId /[a-z0-9]*\-[a-z0-9]*\-[a-z0-9]*\-[a-z0-9]*\-[a-z0-9]/

        [FILTER]
            Name record_modifier
            Match *
            Remove_key message

        [OUTPUT]
            Name  es
            Match *
            Host ${ES_HOST}
            Port 443
            HTTP_User ${ES_USERNAME}
            HTTP_Passwd ${ES_PASSWORD}
            Logstash_Format On
            Logstash_Prefix observables
            Retry_Limit 5
            Type observables
            Index observables-%{+YYYY.MM.dd}
            tls On

        [OUTPUT]
            Name stdout
            Match *
