---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana
    cluster: observables.kibana
  name: kibana
  namespace: observables
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
      cluster: observables.kibana
  template:
    metadata:
      labels:
        app: kibana
        cluster: observables.kibana
    spec:
      serviceAccountName: kibana
      containers:
        - name: sidecar
          image: 'docker-dev.production.deciphernow.com/deciphernow/gm-proxy:1.2.2'
          imagePullPolicy: IfNotPresent
          args:
            - -c
            - /etc/greymatter/config.yaml
          command:
            - /app/gm-proxy
          ports:
            - name: metrics
              containerPort: 8080
            - name: sidecar
              containerPort: 8443
          volumeMounts:
            - name: sidecar-config
              mountPath: /etc/greymatter
              readOnly: true
            - name: spire-socket
              mountPath: /run/spire/sockets
              readOnly: false
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
      imagePullSecrets:
        - name: docker-dev.production.deciphernow.com
      volumes:
        - name: sidecar-config
          configMap:
            name: kibana-sidecar
        - name: spire-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
