apiVersion: v1
kind: LimitRange
metadata:
  name: observables-lr
  namespace: observables
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 200m
    defaultRequest:
      memory: 128Mi
      cpu: 15m
    type: Container