---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash
  namespace: observables
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: logstash
      cluster: observables.logstash
  serviceName: logstash
  template:
    metadata:
      labels:
        app: logstash
        cluster: observables.logstash
    spec:
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash-oss:7.4.2
          imagePullPolicy: Always
          env:
            - name: ES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: logstash-elasticsearch
                  key: username
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logstash-elasticsearch
                  key: password
            - name: ES_HOST
              value: https://vpc-covidapihub-v4j46vkvupaulmzmhqzsnk5c5q.us-east-1.es.amazonaws.com:443
            - name: KAFKA_SERVERS
              value: b-1.covidapihub-observable.y8lgoi.c6.kafka.us-east-1.amazonaws.com:9094,b-2.covidapihub-observable.y8lgoi.c6.kafka.us-east-1.amazonaws.com:9094,b-3.covidapihub-observable.y8lgoi.c6.kafka.us-east-1.amazonaws.com:9094
          volumeMounts:
            - name: logstash-data
              mountPath: /usr/share/logstash/data
            - name: logstash-pipelines
              mountPath: /usr/share/logstash/pipeline
            - name: logstash-templates
              mountPath: /usr/share/logstash/templates
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: logstash-pipelines
          configMap:
            defaultMode: 420
            name: logstash-pipelines
        - name: logstash-templates
          configMap:
            defaultMode: 420
            name: logstash-templates
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: logstash-data
        namespace: observables
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
