---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: observables
  labels:
    app: logstash
    cluster: observables.logstash
spec:
  ports:
    - port: 5044
      protocol: TCP
  selector:
    app: logstash
    cluster: observables.logstash
  type: ClusterIP