apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-logstash
  labels:
    app: nginx-logstash
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
