apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-disease
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: admin@greymatter.io
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-production-disease
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: nginx-disease
            