apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: admin@greymatter.io
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - selector:
          dnsZones:
            - "greymatter.services"
        dns01:
          route53:
            region: us-east-1
            accessKeyID: AKIA6MJIHEYCC52I5FC3
            secretAccessKeySecretRef:
              name: route53-aws-creds
              key: secretAccessKey

# Original clusterissuer for disease.sh using http challenge
# apiVersion: cert-manager.io/v1alpha2
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-production-disease
# spec:
#   acme:
#     # The ACME server URL
#     server: https://acme-v02.api.letsencrypt.org/directory
#     # Email address used for ACME registration
#     email: admin@greymatter.io
#     # Name of a secret used to store the ACME account private key
#     privateKeySecretRef:
#       name: letsencrypt-production-disease
#     # Enable the HTTP-01 challenge provider
#     solvers:
#       - http01:
#           ingress:
#             class: nginx-disease
            
