---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: cert-manager-cainjector:leaderelection
  namespace: kube-system
  labels:
    app: cainjector
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: cainjector
    helm.sh/chart: cert-manager-v0.14.2
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - create
  - update
  - patch
