apiVersion: v1
kind: LimitRange
metadata:
  name: cert-manager-lr
  namespace: cert-manager
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 200m
    defaultRequest:
      memory: 128Mi
      cpu: 1m
    type: Container