apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker.greymatter.io
  namespace: sense
spec:
  encryptedData:
    .dockerconfigjson: AgAiE0MhIpfxtBR0DCISzlXi4WgjydO1qh1RMn/ZkRl0asl/CPrkvSk68dfmLcQF2E0aT/4MfD8yjqwpnj1VjZj8iQgVHYwAvpgMn7L0t+PmGoUyJVRhpfvaNXq/uHtTl0OdCwc41IYfwTrH8a6e2aDzSi/T0O0WyDiSRM2nSZ7fauQ5mUXl7d/UWIKQpTh/OHLiUdOe9uBA8YOj1q1uKJ/+HgxuUDnnLQBLQqVklOLyx5+2NTDqs2lVv0HqvRR3R1GEDDG79DuGzrau1JFRxbxLj6csa/sq7iYINqdZUCTvM34ClDuGpoR5rZTm6TTqXlkO97ZbyLhPB1d7qpziDdb28y3RzPNGEsdMm5Sn/mpMi364WLO6gzDa5tl6/ZWjEio6j7dTFplxyQZir+oguDvzwbh5xmv8NB1Nt8YqldJMvWG/Rlv7RqMtQmqkvpb3KhldqXUhte2FpFVuxE0z+Nqzsy+KUGO/RE6ubZnPM3l7N8MOCij0ToqFU92Yo3Ts45mOhZusSe1YHIH40EuoOd+ZqYkbqUEdoM5PwMzjCmOGRtsnxBa4nmQtq1S4n6o78DJ2kUzOnH4wOxIAuvQKqLZlSTg9KSwp8KSRRsnRqvqvgxH/9XM/XLlZPZSzxIft8VXzOvXZONocKKb8r5+5ZzcZeWZsCcxTFqpWNk3ZbZp6QwDQ9AqsYEkcCiucgE1f1Q96tc7lhv+VT89pr82uUqmuE8LSxaPPyzcvknh/OkgMWhtaxOa2Ju9WWNk6rFZPWJHy3chqWijbTqQ7WTQmeGl9WF/xHeB4/jiRRDOFBYXJjYuxHqepLSAFlGIsRyDC69xvrC4UJXKX6mYg6mppebj6kBBo1ZkSUvqkZBS5d/qVd5MzE/CkJCqLRWYDJnvnVcEABodBXEZhrdQYnBgtHsFDZBGiFhe7h9EsqlzCb5zFny27cJ3xz705hEFBWsoKumyrUeUVq+ng6Jt+2bNUmCTpZmhT
  template:
    metadata:
      creationTimestamp: null
      name: docker.greymatter.io
      namespace: sense
    type: kubernetes.io/dockerconfigjson

