apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker.production.deciphernow.com
  namespace: sense
spec:
  encryptedData:
    .dockerconfigjson: AgAh8gDdCqEYQQoVTXAVAXhvK3lUMXFIUw8/byu+bYxaenQeoB1mVQ4snniwI/bccKkvwts8kX92iu+VQcoU7UZarH94s71EnVzZVtYHMbufw4YIGQ13xwZPvXvkzI89kX/4XwKEG0AhlBgJGL9PQHpZ2FSQxNhR77B0OwrZOzQbPh/QzjoZYAbM8PnL8lX1houptP6NtVW8AcGHPiARg2aodGwq6psSITPQA/qaaPH70hA7TLdOumMdINoQFrb/NA/g6iqBMFDDE83/j0UOrOWozgrK0Gb8wpA9umUQ1Bi2F8e6YoSKvv7EC7okcVJ9INXQFdWnn0axWen6nS1in4I/XloU1K1MHLOQDoXYgI8B77L1PR60TKGgkipmEr3Lnrl4BqtFjqSdNGK3cAXS52xCUzj6wxBf2HgbtX+AqDIWiINAYwWuXGG7CxVtCK5MD2D5Itqghaa8/L7qiMSBoBF3TMpz7ADfJ/rO7xVUoMYpGMlxJMrOxUTqSgnQFCO+Fi803yvIx6bB0T7i6sqoguo2f9uSv+9QX0UdcXLYpTTFgG/sKnoEZ22K2RmXpTLqVibrmbv28CG+FNPAaOzsUETz6Y5c/wxBEdyecZJlxyRK73JFKt5VlMa5A0bAfrdqQ8qxypjNnIGFSnlInscxzTm+NNzGZ42FJSmwkheooczpkRFgSD5LETlpQC1tzypCuHOCtGgLr2UdX9gAtNLW+qB2j49DKAXwHG/y6S1Dp3P5dmSvGVVsCxSlHrez9B3QcsWHqhJACc3kpir6iNAw24dKdjS2ApiUIWmZzZ1KTpwoW1K/OH2PJPTXgYjQiMGNoYIl51Pmq2M=
  template:
    metadata:
      creationTimestamp: null
      name: docker.production.deciphernow.com
      namespace: sense
    type: kubernetes.io/dockerconfigjson

