apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: index.docker.io
  namespace: sense
spec:
  encryptedData:
    .dockerconfigjson: AgB/w0jze9PTxg88hnkQ115QTThgU26cy/g/9Kn5H6tGejuwoiq8hD+c+6dKVvn2TcvniMn7vgsurJkZ6wnTQWDPJca8rclMuYv6RqUydaIA/XwsENXSS1G2Jakm9GkGuAkUFRVjLRYiXxGoNyyOPBveD0n6yDXqxzUq5w2Ipr3D1rMT38Bz9xcrirZ6s3zDHyoFJjGtPqoUKsIcJHu5BzJT6CzfDQgXZRvuJBMpASN2l0Ru/ckJd4LE+f5O7EtED9rKxZzRk4HV8Qv4km7RwbPOudySgPO+vXpC8aK4T65dYp/4mUY5FoouvNmVmWXiWp6gFPotP9p2WjZQsWpBQV1w1dawLLqdIh6dwYl2xx24/ODro3JYnfPOiJYPeiGTBNNRn71maKj2JWV6jABSglnP0GIHRz0rGA+n/x0PWmUN3O5wRjI4msfZPTzVND99nPxwnTYQ0NGcFkZN2IrdU5rTolH7FvasNH5M2G+hGJ96Ar4TjMAYXrMb7J/uwGasx0BYyDzh54hOyWRCHfqSCYJpsdTockvk3T9UvwacbSO3t1WRRjIkdEK5aqaSRUJ+aMBk2BweRCoNCl4HD+oVOvhweMjW29Z5g6BIcvVi9OIxKrYHnQVofRQ302bEuTGI8iNqLqADNtGThGwEA5ifaDupeP3D5SWC+qGRGXvnvk4HoGihBMG5ddn4YpqacAfZlL30iJ8FqKT0HZmKJisApXIFVdUH9rzHOGGYfHzSCF9HUw+btU4f6yfwpQodz+dJOpRhFbFb3bLJNUQ2lSvaU7oaEChxcx3qb9r3TGlp/RKLfVz9JOUKPNs6unHhRgkFhfLHnClWVVh/xPSJLnLd7ONR/M2LgB9D/P59XO5ImfJN4xV1fR9WtiRGffXd1H/ehVddnrKOPSTEKygk5JKHc5To0lA9hVFb8pVoJlJMVW+neDWWoTzi1CgGgiN7jkhYb9+JFFFgmNyxoeu0/5B1xDGen/4pYRJWwl0UIEJAaAwwiBdilZZfSeYOFRbCBe737DEHOw==
  template:
    metadata:
      creationTimestamp: null
      name: index.docker.io
      namespace: sense
    type: kubernetes.io/dockerconfigjson

