apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: index.docker.io
  namespace: sense
spec:
  encryptedData:
    .dockerconfigjson: AgBe4zrUKNm9jAnu1YADqFSqrdwV9QQEYSOidDtpfva8v1G0Ddy68JmrPI7faLUH//azVO5WOX3zMUJfa2oQ+sVC6jIcNDDdjoxJXIOOCvfBkctxMUlWsGsmhj3l10hjkRBqUh7q0cwCeAnbVkUvoFfxbMtnUqaGZRciz4M2Q/kfQBoyEu2hdc7hmVYSnBHB5g6DDoMte9XOJOz5TpHDfqi/bq2t/suZb9XB7xKX/ycxDhB8duVNTidJhPMBOjTYb08TW8Bc1x1jmsNrX9oUQnkC9AynpKYIFM51r3qfTZ/OEaWYyg9KGO2dILLJ6WuzW/xmF7qxnEW6Sx25fDEF2VRAhbVs/k/BvRKl2elQ5VaRe+QGlzEGs9pgZv+BBrSCO2njQvsN1LFlXc2lkpFJmtkA4PkMug9NKZoW1yak38GA+67IcNxViUxtMa5tBe3wg8+xQOAjOrnF9jUAJR7m9EyDaoT7F12T3ZHH09GuszdC7GP4Ep50lUQj819Emj9dm89KyCaFLi716ddK3UXkTxL7GyoGuy3fsbi5KUM7Mptk6QZHxFGAkf05mqS86lfrZptlZCerwVDr6gs8DH7cidhob3hNjOD3zR9tGAn9bzzWhg7tylkNhjKZRqJQ455d67B2ZDxPsk5yJL26729cxyr9jWJDSymrPLL4O3UOL4XBg4JUipUlzSc3qhpU86Y740EAbC/d8kfCGRl68Thv2Xfr+mrG+1/Ffw+SUXuiV8Eli2q4tMu6g+SxX9En7rCfxuWz0KMnxPe2fdz4eKkBN5Ic0qd4/L2z1qt8z9F87k1U4DjqOmaJVsU4sDusm/jgsQizkPgR9l84VDYhW6Rr5YN4
  template:
    metadata:
      creationTimestamp: null
      name: index.docker.io
      namespace: sense
    type: kubernetes.io/dockerconfigjson
status: {}

