---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sense:prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: sense
roleRef:
  kind: ClusterRole
  name: sense:prometheus
  apiGroup: rbac.authorization.k8s.io
